### ISSUE TITLE
Links with the differents solvers on your benchmark

### ISSUE THREAD

**Issue by HilaireFoillard** [mattmilten/mittelmann-plots#3]
Hello, I found your work on benchmarking solvers very interresting, and I'd like to discover the differents solvers you try. But sometimes I don't know what is the solver you name or  where you find it (for exemple I know what is SCIP but I don't know SCIPC). So is it possible to put the website link of the differents solvers you test on your benchmark page and the parameters you use if you try many times the same solvers using different tuning parameters. 

Thank you a lot (and sorry if make writting mistakes, i'm not English)

**Comment by mattmilten** [comment]
Hi!
I am happy to hear that you like my work! Please note that I am relying on the benchmarks conducted by Prof. Hans Mittelmann and am providing a nicer way to inspect his results. I am not running those benchmarks myself. I am also adopting the names that Hans is using. In your case, SCIPC stands for SCIP using CPLEX as LP solver instead of the default SoPlex.

Still, I understand your confusion and will try to add links to the solver webpages somehow.

Do you have further questions?

Cheers
Matthias

**Comment by HilaireFoillard** [comment]
Yes, I find it interesting to compare the performances of the differents solvers and the fact is this benchmark is very accurate ! 
Another interesting benchmark should be comparing the constraint programming solvers.

**Comment by mattmilten** [comment]
Please contact Hans Mittelmann directly concerning new types of benchmarks.
